logging:
  level:
    root: INFO
    com.ihg.soda: info
#    org.springframework: info

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

vending-machine:
  currency-code: USD
  max-count: 10
  queues: 5
  
inventory:
  products:
  - brand: coke-zero
    packaging: can
    upc: 12345
  - brand: coke-zero
    packaging: bottle
    upc: 54321
  - brand: fanta
    packaging: bottle
    upc: 23456
  - brand: seven-up
    packaging: bottle
    upc: 34567
  - brand: seven-up
    packaging: can
    upc: 76543
   