package com.ihg.soda.enums;

public enum MachineStates {
	AWAIT_PAYMENT, 
	CARD_SWIPED, 
	CARD_READ_ERROR, 
	PAYMENT_COMPLETE, 
	HAS_CURRENCY, 
	CHANGE_DUE,
	OUT_OF_BEVERAGE,
	DISPENSE_CURRENCY, 
	DISPENSE_PRODUCT;
}
